USE [University]

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Students'))
BEGIN
  CREATE TABLE Students
  (
    student_id IDENTITY(1,1) INT NOT NULL,
    name VARCHAR(128) NOT NULL,
    CONSTRAINT [PK_Students] PRIMARY KEY CLUSTERED 
		(
			[student_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
  ) ON [PRIMARY] 
END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Enrollments'))
BEGIN
  CREATE TABLE Enrollments
  (
    course_id INT NOT NULL,
    student_id INT NOT NULL,
    type VARCHAR(128),
	CONSTRAINT [PK_Enrollments] PRIMARY KEY CLUSTERED 
		(
			[course_id], [student_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
  ) ON [PRIMARY]  
END;

IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Courses'))
BEGIN
  CREATE TABLE Courses
  (
    course_id IDENTITY(1,1) INT NOT NULL,
    discipline VARCHAR(256) NOT NULL,
	CONSTRAINT [PK_Courses] PRIMARY KEY CLUSTERED 
		(
			[course_id] ASC
		) WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON)
  ) ON [PRIMARY]  
END;

ALTER TABLE Enrollments
    ADD    FOREIGN KEY (course_id)
    REFERENCES Courses(course_id)
    ON DELETE CASCADE
;
    
ALTER TABLE Enrollments
    ADD    FOREIGN KEY (student_id)
    REFERENCES Students(student_id)
    ON DELETE CASCADE
;